### ISSUE TITLE
Some issue when i reproduce.can someone  help me 

### ISSUE THREAD

**Issue by Muuuchen** [microsoft/nnfusion#527]

**Comment by Muuuchen** [comment]
4. There is also a issue 

Traceback (most recent call last):
  File "nasrnn.py", line 154, in <module>
    workflow_search_flag(model, f"nasrnn_bs{args.bs}", (inputs,), args.platform, args.measure, enable_control_flow=args.cf)
  File "/root/nnfusion/artifacts/ast_analyzer/workflow.py", line 191, in workflow_search_flag
    search_best_flags(model, inp, to_import_list, platform)
  File "/root/nnfusion/artifacts/ast_analyzer/tensor_opt/search_best_flags.py", line 212, in search_best_flags
    best_id = run_main_test(work_dir, len(flags_to_try), platform)
  File "/root/nnfusion/artifacts/ast_analyzer/tensor_opt/search_best_flags.py", line 192, in run_main_test
    assert best_id != -1, "No valid flag found"
AssertionError: No valid flag found

when i run `python3 nasrnn.py --platform V100 --bs 64 --no-torch --measure` 。
######################
about 3,i consider its reason is permisson ,but i give the relative files 777 ,it doesn't work
